require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.1.1
  NewCops: enable
  Exclude:
    - bin/**/*
    - config/**/*
    - db/schema.rb
    - db/migrate/**/*
    - lib/tasks/*.rake
    - public/**/*
    - tmp/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['context', 'describe', 'feature', 'let', 'scenario']

Layout/LineLength:
  Max: 130

Metrics/ClassLength:
  Enabled: false
