version: "3"

services:
  db:
    container_name: challenge_db
    image: "postgres:12.3"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=passwd
    ports:
      - 5432:5432