default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: ruby_challenge_development

test:
  <<: *default
  database: ruby_challenge_test

production:
  <<: *default
  database: ruby_challenge_production
  username: ruby_challenge
  password: <%= ENV["RUBY_CHALLENGE_DATABASE_PASSWORD"] %>
